baseurl = "/"
languageCode = "en-us"
title = "Using Databases in R"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[params]

  favicon = "favicon.png"

	[params.palette]
    	primary = "light-blue"
    	accent  = "green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[[menu.main]]
  weight = 5
	name   = "Getting started"
	url    = "/getting-started/"

[[menu.main]]
  weight = 7
	name   = "Connect to a Database"
	url    = "connect/"

[[menu.main]]
  weight = 10
	name   = "Analyzing"
	url    = "/"

[[menu.main]]
  weight = 11
	name   = "dplyr package"
	url    = "dplyr/"
	parent = "Analyzing"

[[menu.main]]
  weight = 12
	name   = "DBI package"
	url    = "dbi/"
	parent = "Analyzing"


[[menu.main]]
  weight = 30
	name   = "Best Practices"
	url    = "/"

[[menu.main]]
  weight = 31
	name   = "Simplify connections"
	url    = "config/"
	parent = "Best Practices"

[[menu.main]]
  weight = 32
	name   = "Secure credentials"
	url    = "keyring/"
	parent = "Best Practices"	

[[menu.main]]
  weight = 33
  name   = "Deploying content"
  url    = "deployment/"
  parent = "Best Practices"

[[menu.main]]
  weight = 40
	name   = "Examples"
	url    = "examples/"

[[menu.main]]
  weight = 50
	name   = "References"
	url    = "reference/"



[social]
	twitter = "rstudio"
	github  = "rstudio"
	email   = "info@rstudio.com"




